// Package swag Code generated by swaggo/swag. DO NOT EDIT
package swag

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "sfshf",
            "url": "https://github.com/sfshf",
            "email": "Z1614789743@outlook.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/sfshf/gonoweb/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/casbin/domain/:dxid/role": {
            "get": {
                "description": "获取域租户的角色列表",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Casbin"
                ],
                "summary": "获取域租户的角色列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "域租户的xid",
                        "name": "dxid",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            }
        },
        "/casbin/domain/:dxid/role/:rxid/resource": {
            "get": {
                "description": "获取域租户的某个角色的资源列表",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Casbin"
                ],
                "summary": "获取域租户的某个角色的资源列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "域租户的xid",
                        "name": "dxid",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "角色的xid",
                        "name": "rxid",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "给域租户的角色分配资源",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Casbin"
                ],
                "summary": "给域租户的角色分配资源",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "域租户的xid",
                        "name": "dxid",
                        "in": "path"
                    },
                    {
                        "type": "string",
                        "description": "角色的xid",
                        "name": "rxid",
                        "in": "path"
                    },
                    {
                        "description": "分配所需参数",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_app_web_ginsrv_casbin.AllocDomainRoleResourcesReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            }
        },
        "/casbin/user/:xid": {
            "post": {
                "description": "给用户分配域租户内的角色",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Casbin"
                ],
                "summary": "给用户分配域租户内的角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户的xid",
                        "name": "xid",
                        "in": "path"
                    },
                    {
                        "description": "分配所需参数",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_app_web_ginsrv_casbin.AllocRolesInDomainReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            }
        },
        "/casbin/user/:xid/domain": {
            "get": {
                "description": "用户被分配到的域租户列表",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Casbin"
                ],
                "summary": "用户被分配到的域租户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户的xid",
                        "name": "xid",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            }
        },
        "/casbin/user/:xid/domain/:dxid/role": {
            "get": {
                "description": "用户在域租户内的角色列表",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Casbin"
                ],
                "summary": "用户在域租户内的角色列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户的xid",
                        "name": "xid",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            }
        },
        "/domain": {
            "get": {
                "description": "获取域租户列表",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "域租户"
                ],
                "summary": "获取域租户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "\u003c=0 获取所有；\u003e0 进行分页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "\u003c=0 获取所有；\u003e0 进行分页",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_app_web_ginsrv_domain.ListDomainResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "新增域租户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "域租户"
                ],
                "summary": "新增域租户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "域租户信息",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_app_web_ginsrv_domain.AddDomainReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TDomain"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            }
        },
        "/domain/:xid": {
            "get": {
                "description": "获取域租户信息",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "域租户"
                ],
                "summary": "获取域租户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "域租户xid",
                        "name": "xid",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TDomain"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "编辑域租户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "域租户"
                ],
                "summary": "编辑域租户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "域租户xid",
                        "name": "xid",
                        "in": "path"
                    },
                    {
                        "description": "域租户信息",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_app_web_ginsrv_domain.EditDomainReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除域租户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "域租户"
                ],
                "summary": "删除域租户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "域租户xid",
                        "name": "xid",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "测试服务路由是否正常服务",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "测试"
                ],
                "summary": "测试服务路由",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/resource": {
            "get": {
                "description": "获取菜单/控件/API列表",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单/控件/API"
                ],
                "summary": "获取菜单/控件/API列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "name": "identifier",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "\u003c=0 获取所有；\u003e0 进行分页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "\u003c=0 获取所有；\u003e0 进行分页",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_app_web_ginsrv_resource.ListResourceResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "新增菜单/控件/API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单/控件/API"
                ],
                "summary": "新增菜单/控件/API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "菜单/控件/API信息",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_app_web_ginsrv_resource.AddResourceReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TResource"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            }
        },
        "/resource/:id": {
            "get": {
                "description": "获取菜单/控件/API信息",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单/控件/API"
                ],
                "summary": "获取菜单/控件/API信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "菜单/控件/API的id",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TResource"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "编辑菜单/控件/API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单/控件/API"
                ],
                "summary": "编辑菜单/控件/API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "菜单/控件/API的id",
                        "name": "id",
                        "in": "path"
                    },
                    {
                        "description": "菜单/控件/API信息",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_app_web_ginsrv_resource.EditResourceReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除菜单/控件/API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜单/控件/API"
                ],
                "summary": "删除菜单/控件/API",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "菜单/控件/API的id",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            }
        },
        "/role": {
            "get": {
                "description": "获取角色列表",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色"
                ],
                "summary": "获取角色列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "name": "dxid",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "\u003c=0 获取所有；\u003e0 进行分页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "\u003c=0 获取所有；\u003e0 进行分页",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_app_web_ginsrv_role.ListRoleResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "新增角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色"
                ],
                "summary": "新增角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "角色信息",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_app_web_ginsrv_role.AddRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TRole"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            }
        },
        "/role/:xid": {
            "get": {
                "description": "获取角色信息",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色"
                ],
                "summary": "获取角色信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "角色xid",
                        "name": "xid",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TRole"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "编辑角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色"
                ],
                "summary": "编辑角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "角色xid",
                        "name": "xid",
                        "in": "path"
                    },
                    {
                        "description": "角色信息",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_app_web_ginsrv_role.EditRoleReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "角色"
                ],
                "summary": "删除角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "角色xid",
                        "name": "xid",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            }
        },
        "/user": {
            "get": {
                "description": "获取用户列表",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取用户列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "name": "email",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "nickname",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "\u003c=0 获取所有；\u003e0 进行分页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "\u003c=0 获取所有；\u003e0 进行分页",
                        "name": "pageSize",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "realname",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_app_web_ginsrv_user.ListUserResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "用户切换角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户切换角色",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "name": "dxid",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "name": "rxid",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_service_user.SignInData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            },
            "post": {
                "description": "新增用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "新增用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "用户信息",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_app_web_ginsrv_user.AddUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TUser"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            }
        },
        "/user/:xid": {
            "get": {
                "description": "获取用户信息",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取用户信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户xid",
                        "name": "xid",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TUser"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            },
            "put": {
                "description": "编辑用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "编辑用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户xid",
                        "name": "xid",
                        "in": "path"
                    },
                    {
                        "description": "用户信息",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/internal_app_web_ginsrv_user.EditUserReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            },
            "delete": {
                "description": "删除用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "string",
                        "description": "用户xid",
                        "name": "xid",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            }
        },
        "/user/agent": {
            "get": {
                "description": "获取用户访问/登录记录列表",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "获取用户访问/登录记录列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "type": "integer",
                        "description": "\u003c=0 获取所有；\u003e0 进行分页",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "\u003c=0 获取所有；\u003e0 进行分页",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_app_web_ginsrv_user.ListUserAgentResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            }
        },
        "/user/signIn": {
            "post": {
                "description": "用户登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录所需参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_app_web_ginsrv_user.SignInReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_service_user.SignInData"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            }
        },
        "/user/signOut": {
            "post": {
                "description": "用户登出",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户登出",
                "parameters": [
                    {
                        "type": "string",
                        "description": "登录token",
                        "name": "Authorization",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            }
        },
        "/user/visit": {
            "post": {
                "description": "用户首次打开页面，上报用户代理、时区、语言等信息",
                "consumes": [
                    "text/plain"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户"
                ],
                "summary": "用户首次访问时信息上报",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_app_web.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_sfshf_gonoweb_internal_app_web.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        },
        "github_com_sfshf_gonoweb_internal_model.TDomain": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "intro": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "xid": {
                    "type": "string"
                }
            }
        },
        "github_com_sfshf_gonoweb_internal_model.TResource": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "integer"
                },
                "icon": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "identifier": {
                    "type": "string"
                },
                "intro": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "github_com_sfshf_gonoweb_internal_model.TRole": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "intro": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "xid": {
                    "type": "string"
                }
            }
        },
        "github_com_sfshf_gonoweb_internal_model.TUser": {
            "type": "object",
            "properties": {
                "avatar": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nick_name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                },
                "real_name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "xid": {
                    "type": "string"
                }
            }
        },
        "github_com_sfshf_gonoweb_internal_model.TUserAgent": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "deleted_at": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "ip": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                },
                "trace_id": {
                    "type": "string"
                },
                "ua": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_xid": {
                    "type": "string"
                }
            }
        },
        "github_com_sfshf_gonoweb_internal_service_user.SignInData": {
            "type": "object",
            "properties": {
                "domain": {
                    "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TDomain"
                },
                "menus": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TResource"
                    }
                },
                "role": {
                    "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TRole"
                },
                "token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TUser"
                },
                "widgets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TResource"
                    }
                }
            }
        },
        "internal_app_web_ginsrv_casbin.AllocDomainRoleResourcesReq": {
            "type": "object",
            "properties": {
                "identifiers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_app_web_ginsrv_casbin.AllocRolesInDomainReq": {
            "type": "object",
            "required": [
                "domain"
            ],
            "properties": {
                "domain": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_app_web_ginsrv_domain.AddDomainReq": {
            "type": "object",
            "properties": {
                "intro": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_app_web_ginsrv_domain.EditDomainReq": {
            "type": "object",
            "properties": {
                "intro": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_app_web_ginsrv_domain.ListDomainResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TDomain"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_app_web_ginsrv_resource.AddResourceReq": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string"
                },
                "identifier": {
                    "type": "string"
                },
                "intro": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "integer",
                    "enum": [
                        1,
                        2,
                        3
                    ]
                }
            }
        },
        "internal_app_web_ginsrv_resource.EditResourceReq": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string"
                },
                "intro": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_app_web_ginsrv_resource.ListResourceResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TResource"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_app_web_ginsrv_role.AddRoleReq": {
            "type": "object",
            "properties": {
                "intro": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_app_web_ginsrv_role.EditRoleReq": {
            "type": "object",
            "properties": {
                "intro": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_app_web_ginsrv_role.ListRoleResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TRole"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_app_web_ginsrv_user.AddUserReq": {
            "type": "object",
            "required": [
                "email",
                "nickname"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                }
            }
        },
        "internal_app_web_ginsrv_user.EditUserReq": {
            "type": "object",
            "required": [
                "email",
                "nickName"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "nickName": {
                    "type": "string"
                }
            }
        },
        "internal_app_web_ginsrv_user.ListUserAgentResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TUserAgent"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_app_web_ginsrv_user.ListUserResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_sfshf_gonoweb_internal_model.TUser"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "internal_app_web_ginsrv_user.SignInReq": {
            "type": "object",
            "required": [
                "account",
                "password"
            ],
            "properties": {
                "account": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "192.168.211.128:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Gono Web API",
	Description:      "This is a web api server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
