// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTDomain = "t_domain"

// TDomain mapped from table <t_domain>
type TDomain struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt int64     `gorm:"column:deleted_at;not null" json:"deleted_at"`
	Xid       string    `gorm:"column:xid;not null" json:"xid"`
	Name      string    `gorm:"column:name;not null" json:"name"`
	Intro     string    `gorm:"column:intro" json:"intro"`
}

// TableName TDomain's table name
func (*TDomain) TableName() string {
	return TableNameTDomain
}
