// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTUserAgent = "t_user_agent"

// TUserAgent mapped from table <t_user_agent>
type TUserAgent struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	UserXid   string         `gorm:"column:user_xid" json:"user_xid"`
	IP        string         `gorm:"column:ip;not null" json:"ip"`
	Ua        string         `gorm:"column:ua;not null" json:"ua"`
	TraceID   string         `gorm:"column:trace_id;not null" json:"trace_id"`
	Token     string         `gorm:"column:token" json:"token"`
}

// TableName TUserAgent's table name
func (*TUserAgent) TableName() string {
	return TableNameTUserAgent
}
